### ISSUE TITLE
Leaderboard clean up

### ISSUE THREAD

**Issue by zakiya** [cagov/leaderboard#17]
Please remove these sites and any others that redirect to a login page. 

- [Epanet.ca.gov](http://epanet.ca.gov/) – it’s supposed to be an intranet site and not meant to be a public URL.
- [www.calcompetes.ca.gov/Login.aspx?ReturnUrl=%2fREDIRECT](http://www.calcompetes.ca.gov/Login.aspx?ReturnUrl=%2fREDIRECT) FROM [calcompetes.ca.gov/](http://calcompetes.ca.gov/)
-  [login.microsoftonline.com/52b26be4-7f5d-4e1c-baed-8cf75b7570d5/saml2REDIRECT](http://login.microsoftonline.com/52b26be4-7f5d-4e1c-baed-8cf75b7570d5/saml2REDIRECT) FROM [access2.ca.gov/](http://access2.ca.gov/)

**Comment by xjensen** [comment]
The first [commit](https://github.com/cagov/leaderboard/commit/240cfddbf1d410c083e4f187a6471a1fc114ef9a) predates this issue by a few minutes. 😅

Cleaning up the rest of the list is going to require time and care. It's a tedious process.

**Comment by zakiya** [comment]
Closing until/unless we get further direction from Art
